### ISSUE TITLE
Code blocks in collapsible sections render before section

### ISSUE THREAD

**Issue by CosmicHorrorDev** [Inlyne-Project/inlyne#107]
**Repro**

````markdown
<details>
<summary>Repro</summary>

Before the code block

```rust
fn main() {}
```

After the code block

</details>
````

---

**Rendered by GitHub**

<details>
<summary>Repro</summary>

Before the code block

```rust
fn main() {}
```

After the code block

</details>

---

**Rendered by `inlyne`**

![image](https://github.com/trimental/inlyne/assets/30302768/43d08121-0a1d-4eb3-8c65-586ead598cd6)

![image](https://github.com/trimental/inlyne/assets/30302768/83a2efbc-4911-4447-99ae-7e80830081a7)

**Comment by kokoISnoTarget** [comment]
Is this up to date?

Tested with 4.1
![Screenshot_2024-03-28-01-55-32_5120x1263](https://github.com/Inlyne-Project/inlyne/assets/72217393/cd32e443-51fd-4b7a-b4cc-da85a8c3b3b7)

**Comment by CosmicHorrorDev** [comment]
Thanks for checking! It does look like this got fixed at some point :sweat_smile:
