### ISSUE TITLE
Header sizes should be relative to text size

### ISSUE THREAD

**Issue by CosmicHorrorDev** [Inlyne-Project/inlyne#201]
With the still-pedning-release text rewrite one of the unreleased changes caused header sizes to grow much smaller than the regular text's size now. The header sizes should be adjusted to reflect the new text size and should probably use multipliers to be more resilient to these kinds of changes in the future

---

## Markdown

```markdown
# H1
## H2
### H3
#### H4
##### H5
###### H6

Regular text
```

---

## Rendered by GitHub

# H1
###### H6

Regular text

---

## Rendered by `inlyne`

![image](https://github.com/trimental/inlyne/assets/30302768/714a3e3b-8efb-4daf-8e7b-fafdf4ed83b9)

**Comment by Valentin271** [comment]
Maybe github renders differently on your screen, but on mine the text is actually equivalent to h4, meaning h5 and h6 are smaller. This is hard to see but looking at the CSS this is pretty clear.

- `h1`: `2em`
- `h2`: `1.5em`
- `h3`: `1.25em`
- `h4`: `1em`
- `h5`: `.875em`
- `h6`: `.85em`
- `text`: `14px`

I agree though that we should start using relative sizes for headers. We can probably align on github sizes.

**Comment by CosmicHorrorDev** [comment]
Well that's a TIL. Thanks for the investigation!
