### ISSUE TITLE
0.4.0 release crashes on NetBSD

### ISSUE THREAD

**Issue by 0323pin** [Inlyne-Project/inlyne#248]
Hi,

Just finished updating our package to 0.4.0
Launching `inlyne` crashes with the following report:

```
"name" = "inlyne"
"operating_system" = "NetBSD 10.99.10 [64-bit]"
"crate_version" = "0.4.0"
"explanation" = """
Panic occurred in file '/usr/pkgsrc/wip/inlyne/work/vendor/cosmic-text-0.9.0/src/shape.rs' at line 174
"""
"cause" = "no default font found"
"method" = "Panic"
"backtrace" = """

   0:   0x580bb3 - <unresolved>
   1:  0x1072345 - <unresolved>
   2:  0x1073ee9 - <unresolved>
   3:  0x1074704 - <unresolved>
   4:  0x1075255 - <unresolved>
   5:  0x106df20 - <unresolved>
   6:  0x106e11e - <unresolved>
   7:  0x1067b32 - <unresolved>
   8:  0x1067c79 - <unresolved>
   9:   0x5e018e - <unresolved>
  10:   0x5de688 - <unresolved>
  11:   0x6625c4 - <unresolved>
  12:   0x66a571 - <unresolved>
  13:   0x5f2b7c - <unresolved>
  14:   0x6b1973 - <unresolved>
  15:   0x6b3355 - <unresolved>
  16:   0x66c057 - <unresolved>
  17:   0x6b5593 - <unresolved>
  18:   0x61b39d - <unresolved>
  19:  0x148f302 - <unresolved>
  20:   0x61b38e - <unresolved>
  21:   0x4fc3dd - <unresolved>"""
```

**EDIT:** `"cause" = "no default font found"`? I use `FantasqueSansMNerdFont Mono`
Where should the default font be defined? And, where is it looking for fonts?
On NetBSD fonts are located in `/usr/pkg/share/fonts/X11`

**Comment by 0323pin** [comment]
@CosmicHorrorDev Edited the initial post with a few questions and notes.

**Comment by 0323pin** [comment]
> Thanks for the issue! Can you try out this branch and see if that fixes your problems?
> 
> https://github.com/CosmicHorrorDev/inlyne/tree/fontconfig-glyphon

Yes, I can do that but, unfortunately only tomorrow. I'll get back to you once I've done it.

**Comment by 0323pin** [comment]
@CosmicHorrorDev I can confirm that building from this branch fixes the issue, thank you!

Should I patch 0.4.0 locally or, can you do a point release with the fix included?

**Comment by CosmicHorrorDev** [comment]
I can do a point release later tomorrow :D

**Comment by 0323pin** [comment]
Thank you, I'll wait for that than. No rush, have a rest :)

**Comment by CosmicHorrorDev** [comment]
Release is out :tada: 

Thanks again for the issue!
