### ISSUE TITLE
Inlyne segfaults on any file input (macOS, Rust 1.76.0)

### ISSUE THREAD

**Issue by ndaniels** [Inlyne-Project/inlyne#254]
On macOS Sonoma (14.3), with Rust 1.76.0, having installed via cargo, inlyne segfaults even on a minimal input file -- or even, as I just discovered, if given a nonexistent filename.

**Comment by CosmicHorrorDev** [comment]
If you haven't already can you try building from source and seeing if the issue persists?

**Comment by ndaniels** [comment]
Well, I'd installed using cargo, which did build from source. But I just tried cloning the repo and building, and now get a failure with flate2:

   Compiling flate2 v1.0.28
error[E0635]: unknown feature `stdsimd`

Weirder still, I wanted to see if this now failed if I did a `cargo install` of inlyne, and... it built find and now works. I'm baffled (and I'm not new to Rust). Heisenbugs are hard to debug!

I'll close this for now...
