### ISSUE TITLE
0.4.1 release build crashed on linux

### ISSUE THREAD

**Issue by chenrui333** [Inlyne-Project/inlyne#263]
While trying to [package this project for homebrew](https://github.com/Homebrew/homebrew-core/pull/165639), I ran into some crash while starting the app.

```
runner@fv-az881-710:/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core$ cat /tmp/report-f5c58da5-dd4e-4630-8cf4-ed879b9bb80d.toml
"name" = "inlyne"
"operating_system" = "Ubuntu 22.04 (jammy) [64-bit]"
"crate_version" = "0.4.1"
"explanation" = """
Panic occurred in file '/home/runner/.cache/Homebrew/cargo_cache/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.7/src/platform_impl/linux/[mod.rs](http://mod.rs/)' at line 757
"""
"cause" = "Failed to initialize any backend! Wayland status: XdgRuntimeDirNotSet X11 status: XOpenDisplayFailed"
"method" = "Panic"
"backtrace" = """

   0: 0x557ecb697888 - <unresolved>
   1: 0x557ecb758493 - <unresolved>
   2: 0x557ecb740c3d - <unresolved>
   3: 0x557ecc6a5e24 - <unresolved>
   4: 0x557ecc6a7d1b - <unresolved>
   5: 0x557ecb698aa5 - <unresolved>
   6: 0x7f9ef2029d90 - <unresolved>
   7: 0x7f9ef2029e40 - __libc_start_main
   8: 0x557ecb5ff025 - <unresolved>
   9:        0x0 - <unresolved>"""
```

- wayland, 1.22.0
- libxkbcommon, 1.5.0

**Comment by CosmicHorrorDev** [comment]
Thanks for the issue! I'll try setting up a VM to work on reproing sometime over the next week

**Comment by chenrui333** [comment]
Thanks @CosmicHorrorDev!

**Comment by CosmicHorrorDev** [comment]
Alright, had time to setup an Ubuntu 22.04 VM and I'm able to run the prebuilt binary on a clean install without having to install anything else

![image](https://github.com/Inlyne-Project/inlyne/assets/30302768/aea9647c-7f6a-4e7f-b89f-abccdc53c7c6)

I'm also able to build and run things after installing `cargo`, `gcc` (but any C compiler should do), `libfontconfig-dev`, `libxkbcommon-dev`, and `libwayland-dev` (if building with the `wayland` feature which is on by default)

![image](https://github.com/Inlyne-Project/inlyne/assets/30302768/6c931aae-122a-43fb-87f1-e39e993af689)

---

Not sure where to go from here, but I can provide more information from my system if it helps in tracking down the issue

**Comment by CosmicHorrorDev** [comment]
Can you still reproduce this issue with the latest release? It fixed an issue with mismatched Wayland client/server capabilities

**Comment by chenrui333** [comment]
I will checkout the linux test issue with this pr, https://github.com/Homebrew/homebrew-core/pull/195019

**Comment by chenrui333** [comment]
I think it is just Linux CI issue, gonna close it for now.
