### ISSUE TITLE
crash on startup linux wayland

### ISSUE THREAD

**Issue by Cyrix126** [Inlyne-Project/inlyne#283]
Hello,

I'm using sway 1:1.9-1 and inlyne 0.4.1 crash immediatly (there is just a first frame appearing before closing).
```

"name" = "inlyne"
"operating_system" = "Artix Linux [64-bit]"
"crate_version" = "0.4.1"
"explanation" = """
Panic occurred in file '/home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/khronos-egl-4.1.0/src/lib.rs' at line 1015
"""
"cause" = "called `Option::unwrap()` on a `None` value"
"method" = "Panic"
"backtrace" = """

   0: 0x55d1b1b84062 - <unresolved>
   1: 0x55d1b2798b18 - <unresolved>
   2: 0x55d1b1f843d3 - <unresolved>
   3: 0x55d1b1f8023a - <unresolved>
   4: 0x55d1b1f5e692 - <unresolved>
   5: 0x55d1b1fbc31a - <unresolved>
   6: 0x55d1b1fb976e - <unresolved>
   7: 0x55d1b1f441e3 - <unresolved>
   8: 0x55d1b1fb1142 - <unresolved>
   9: 0x7f5b479c8cd0 - <unresolved>
  10: 0x7f5b479c8d8a - __libc_start_main
  11: 0x55d1b1be9cd5 - <unresolved>
  12:        0x0 - <unresolved>"""
```

Maybe related to https://github.com/Inlyne-Project/inlyne/issues/263 but the panic is not on the same crate.

Version 0.4.0 also crash.
Version 0.3.3 does not have this issue.

I'm ready to offer more information if needed.

**Comment by CosmicHorrorDev** [comment]
It looks like that crash is coming from a dependency used by `wgpu`. It looks like we're currently using an older version of `wgpu` on this release than we were on v0.3.3 (likely due to new dependencies that needed an older version)

I can work on trying to get `wgpu` more up to date to see if that makes the issue go away. In the meantime it looks like there's a newer compatible `wgpu` version you could try by running `cargo update` on the repo and then try running `cargo run -- README.md` and see if that see if that fixes things and if not then we'll have a backtrace that includes debuginfo at least

**Comment by Cyrix126** [comment]
cargo update:

```
Unchanged khronos-egl v4.1.0 (latest: v6.0.0)
Updating wgpu v0.16.1 -> v0.16.3 (latest: v0.19.3) 
```

Looks like khronos dep didn't change, but now the error is not the same.

```
trap at Instance { def: Item(DefId(1:14307 ~ core[f542]::core_arch::x86::sse2::_mm_cvtps_epi32)), args: [] } (_ZN4core9core_arch3x864sse215_mm_cvtps_epi3217h8adb6756d373c84bE): llvm.x86.sse2.cvtps2dq
```

The window close this time a little later with only the first header rendering.
[inlyne_283_1.webm](https://github.com/Inlyne-Project/inlyne/assets/58007246/2f1ae356-6cdd-4f17-93d5-95e70ccf16a3)

**Comment by CosmicHorrorDev** [comment]
Thanks for trying it out!

At least things got a bit further. I'll ping you after updating `wgpu`, so that we can try again, but that likely won't be for another week at least

**Comment by Cyrix126** [comment]
tested with release v0.4.2 and it works.
Thanks !

**Comment by CosmicHorrorDev** [comment]
Oh awesome! Didn't realize that it would fix this, but happy to hear that it's working for you 😊

**Comment by Lynnesbian** [comment]
I'm having this issue myself, on release v0.4.3:
```toml
"name" = "inlyne"
"operating_system" = "Fedora 40.0.0 [64-bit]"
"crate_version" = "0.4.3"
"explanation" = """
Panic occurred in file '/home/lynne/.cargo/registry/src/index.crates.io-6f17d22bba15001f/khronos-egl-4.1.0/src/lib.rs' at line 1015
"""
"cause" = "called `Option::unwrap()` on a `None` value"
"method" = "Panic"
"backtrace" = """

   0: 0x55783289636c - <unresolved>
   1: 0x557832896249 - <unresolved>
   2: 0x5578325f9cb3 - <unresolved>
   3: 0x5578325d4e96 - <unresolved>
   4: 0x55783248094a - <unresolved>
   5: 0x5578324ca7bd - <unresolved>
   6: 0x5578324d860f - <unresolved>
   7: 0x557832555820 - <unresolved>
   8: 0x5578318af270 - <unresolved>
   9: 0x55783192f8c0 - <unresolved>
  10: 0x5578318455d3 - <unresolved>
  11: 0x55783192508d - <unresolved>
  12: 0x5578318b39dc - <unresolved>
  13: 0x557831901983 - <unresolved>
  14: 0x5578318833cd - <unresolved>
  15: 0x55783285b970 - <unresolved>
  16: 0x5578318b4328 - <unresolved>
  17: 0x7f2353f55088 - __libc_start_call_main
  18: 0x7f2353f5514b - __libc_start_main@@GLIBC_2.34
  19: 0x5578317cc9a5 - <unresolved>
  20:        0x0 - <unresolved>"""

```

In addition, inlyne prints `wp_linux_drm_syncobj_surface_v1#38: error 4: explicit sync is used, but no acquire point is set` to `stderr`, followed by a little over six thousand lines of `Protocol error 4 on object wp_linux_drm_syncobj_surface_v1@38:`, then segfaults.

```
❯ inlyne README.md 
wp_linux_drm_syncobj_surface_v1#38: error 4: explicit sync is used, but no acquire point is set
Protocol error 4 on object wp_linux_drm_syncobj_surface_v1@38: 
Protocol error 4 on object wp_linux_drm_syncobj_surface_v1@38: 
Protocol error 4 on object wp_linux_drm_syncobj_surface_v1@38: 
Protocol error 4 on object wp_linux_drm_syncobj_surface_v1@38: 
Protocol error 4 on object wp_linux_drm_syncobj_surface_v1@38: 
Protocol error 4 on object wp_linux_drm_syncobj_surface_v1@38: 
[ ... several thousand lines snipped ... ]
Protocol error 4 on object wp_linux_drm_syncobj_surface_v1@38: 
Protocol error 4 on object wp_linux_drm_syncobj_surface_v1@38: 
Protocol error 4 on object wp_linux_drm_syncobj_surface_v1@38: 
Segmentation fault (core dumped)
```

My system has an Intel iGPU and an Nvidia dGPU. Explicitly running inlyne on the dedicated GPU solves the problem, bar two warnings:

```
❯ DRI_PRIME=pci-0000_01_00_0 __VK_LAYER_NV_optimus=NVIDIA_only __GLX_VENDOR_LIBRARY_NAME=nvidia inlyne README.md 
libEGL warning: egl: failed to create dri2 screen
libEGL warning: egl: failed to create dri2 screen
```

## Environment
Fedora 40, x86_64, KDE spin, Wayland
Kernel: `Linux pasiphael 6.10.10-200.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Sep 12 18:26:09 UTC 2024 x86_64 GNU/Linux`
iGPU: `Mesa Intel(R) UHD Graphics (ADL-S GT1)`
dGPU: `NVIDIA GeForce RTX 4070 Laptop GPU/PCIe/SSE2`, proprietary drivers (version `560.35.03`)
Inlyne version: `0.4.3`, installed via `cargo install inlyne`

---

Potentially relevant: Firefox fixed [a similar crash](https://bugzilla.mozilla.org/show_bug.cgi?id=1898476) a few months ago. I personally never ran in to this Firefox bug, but the logged message about explicit sync being used with no acquire point matches the one reported there.
