### ISSUE TITLE
did 0.4.3 release get re-tagged?

### ISSUE THREAD

**Issue by chenrui333** [Inlyne-Project/inlyne#366]
👋 seeing some checksum changed while regression build the 0.4.3 release, raise this issue to confirm if there was some re-tagging? Thanks!

error log https://github.com/Homebrew/homebrew-core/actions/runs/11393912950/job/31705951453?pr=194802#step:3:8917

relates to https://github.com/Homebrew/homebrew-core/pull/194802

**Comment by CosmicHorrorDev** [comment]
Hmmm, that's odd. Nothing should have changed since the release and the tag along with all of the assets still say that they were created on August 29th

I generally don't like messing with a release after it's cut (aside from fixing issues while trying to cut the release) since it's easier to just push a new release (and registries like crates.io try to be immutable)

**Comment by CosmicHorrorDev** [comment]
It looks like the contents of the extracted tarball still match the contents of the repo at the `v0.4.3` tag. I'm not sure what would cause the checksum to change

```text
inlyne on  HEAD (588687e) is 📦 v0.4.3 via 🦀 v1.82.0
❯ diff -r ~/Downloads/inlyne-0.4.3/ .
Only in .: .git
```

It also looks like whatever checksum gets generated for `nixpkgs` is still the same

https://github.com/NixOS/nixpkgs/blob/d5627dfcd4510a1f874ee2967e72c12efd7feb25/pkgs/applications/misc/inlyne/default.nix#L24

```text
error: hash mismatch in fixed-output derivation '/nix/store/xv70lxwz57idw2wxq4z1qb76422jbls4-source.drv':
         specified: sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
            got:    sha256-j4DEau7LZxIoVIIYwCUgqmkSgdRxWzF5/vOS0lvjgUk=  <-- still gets the same hash
```

I don't think I ever downloaded the old tarball, so I'm not sure of any other ways to check what the old hash could have been :/

**Comment by CosmicHorrorDev** [comment]
From the release workflows it looks like there was one failed release last time before the full workflow managed to succeed. Is it possible that `brew` managed to update things using that tag before things got sorted out and I re-tagged for the current commit it's on?

**Comment by chenrui333** [comment]
> From the [release workflows](https://github.com/Inlyne-Project/inlyne/actions/workflows/release.yml) it looks like there was one failed release last time before the full workflow managed to succeed.

since [this PR](https://github.com/Homebrew/homebrew-core/pull/182830) did not have the release notes, it is likely the bot picked up the tag before the full release flow completes. But still it should be the same tagged commit?

**Comment by chenrui333** [comment]
okay, looks like two commits got mapped into the same tag, which makes sense then. 

![image](https://github.com/user-attachments/assets/60d54c1b-3ca0-4a6d-977c-14ec8992e04f)

**Comment by CosmicHorrorDev** [comment]
That's my thinking as well. I think that's a sufficient enough explanation. It's a situation I try to avoid, but I didn't know about the broken release pipeline till the tag was pushed to trigger it

**Comment by chenrui333** [comment]
yeah, make sense 👍
