### ISSUE TITLE
[Suggestion] History and Navigation

### ISSUE THREAD

**Issue by nerdachse** [Inlyne-Project/inlyne#53]
Hey there!

## Motivation

After #50 is closed, clicking a link to a local `md` file will open it in the current window.

I think it makes sense to add some lightweight "history" and "navigation" in order to be able to go back to the previously opened file.

## Other alternatives

Well, if every markdown file has a link to the previous one, this is a none issue. Like if you create a strict hierarchy. But it relies on the content of the markdown files, which is outside our control.

I think it makes sense to add this, especially now (or rather soonish ;)) that the content of the current window is overwritten.

## To decide

Shortcuts for navigation and maybe even some kind of menu-bar/ui buttons?

**Comment by trimental** [comment]
I think navigation shortcuts would be a good idea however I'm unsure whether ui buttons would be a good fit. One of the reasons (other than being lazy) of avoiding creating a ui interaction bar or something similar, is that it would take up screen space and add visual complexity. 

I like the idea of inlyne being a viewport to the markdown page and nothing more. More of a CLI app that spawns a window than a GUI app that's launched from the terminal.

History shouldn't be hard to track and the framework to implement customisable shortcuts was already made by @LovecraftianHorror. Overall this should be another easy feature to implement :)

**Comment by CosmicHorrorDev** [comment]
This should be possible now in `main` with the `Alt+<left or right arrow>` or the `bp` or `bn` keybinds
