### ISSUE TITLE
[Suggestion] Add brew support (brew formula)

### ISSUE THREAD

**Issue by optimizasean** [Inlyne-Project/inlyne#57]
I think it would greatly help adoption if you added a brew package for this.

This tool is great!

**Comment by optimizasean** [comment]
I don't know how to create these. Never done it before but am reading up on it: https://docs.brew.sh/Formula-Cookbook

**Comment by CosmicHorrorDev** [comment]
This should be resolved after the merge of:

- https://github.com/Homebrew/homebrew-core/pull/165639

**Comment by CosmicHorrorDev** [comment]
We now have a brew formula :tada:

https://formulae.brew.sh/formula/inlyne
